### ISSUE TITLE
Readlogs is loading complete file

### ISSUE THREAD

**Issue by copingone** [x8-ball/ctf_submitter#8]
Should be implemented with buffsize to save ram, else ram is going to run full after a while.

**Comment by x8-ball** [comment]
Totally agree with you. One could implement second function from https://gist.github.com/amitsaha/5990310. It reads the last x lines, without looking at the whole file.

**Comment by x8-ball** [comment]
just implemented some code, but not sure how to check if whole file is loaded

**Comment by copingone** [comment]
Issue indeed fixed.  Good work!
